version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine 
    container_name: user-api-postgres
    environment:
      POSTGRES_USER: eyub
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 
    restart: unless-stopped

volumes:
  pgdata:
